### ISSUE TITLE
2023 Design 01 Multi Assignees accepted

### ISSUE THREAD

**Issue by lmas3009** [lmas3009/design2code2live#126]
Create a folder with the Design 01_2023/{yourname}

Built it using HTML, CSS/Tailwind CSS, Javascript

Optional: Make it Responsive

Note: Add your images, about, live github/dev.to links. **PART 1**
Design 02 is **PART 2**

We accept multiple PR's. This is your personal website. 

**✨✨Do not add the same text as shown**

Design by **Aravind Kumar Vemula**

## Design
![MacBook Pro 16_ - 3](https://github.com/lmas3009/design2code2live/assets/60876387/74d99233-9b51-423a-aa4d-2db80b6c32ed)

## Resources

fonts: https://fonts.google.com
colors: https://coolors.co
images: https://unsplash.com or https://www.pexels.com

**Comment by AayushBiswas** [comment]
Can I work on this issue

**Comment by lmas3009** [comment]
Multiple can work on this issue. @AayushBiswas assigned. Follow the folder naming condition

**Comment by SohamTamhane** [comment]
Can I work on this Issue?

**Comment by lmas3009** [comment]
sure @SohamTamhane

**Comment by lmas3009** [comment]
follow the folder naming format like this
![image](https://github.com/lmas3009/design2code2live/assets/60876387/efa2936c-5d25-4b49-bee4-a3129f192821)

**Comment by purnasth** [comment]
Hello, feel free to assign this task to me.

**Comment by Skb08** [comment]
Hi @lmas3009, I also want to contribute 
Can you assign me.

**Comment by Skb08** [comment]
Can I use bootstrap. @lmas3009

**Comment by lmas3009** [comment]
Yes you can use that
