### ISSUE TITLE
2023 Custom Design (Accept Multiple Assignes)

### ISSUE THREAD

**Issue by lmas3009** [lmas3009/design2code2live#216]
Create the folder based on your project name.

Choose any single-page web designs from dribble/google/Pinterest/etc...

Built it using HTML, CSS/Tailwind CSS, Javascript

Join https://discord.gg/C3PAvsmrKV for fast-updated

Optional: Make it Responsive

Resources
fonts: https://fonts.google.com/
colors: https://coolors.co/
images: https://unsplash.com/ or https://www.pexels.com/

**Comment by zainbinfurqan** [comment]
@lmas3009 can i work on this issue?

**Comment by swetha-Kesara** [comment]
@lmas3009 Hi, please let me know if the issue is available. I am interested in trying to complete it.

**Comment by harrishDev** [comment]
@lmas3009 assign me i'll come up with good looking landing page

**Comment by lmas3009** [comment]
sure @zainbinfurqan @swetha-Kesara @harrishDev You can work.

Make sure you have a unique folder names

**Comment by Ramiz1336** [comment]
I would like to work on this issue

**Comment by lmas3009** [comment]
sure @Ramiz1336

**Comment by priyanshu-gupta0503** [comment]
hey@lmas3009  Would like to work on this pls assign this to me.

**Comment by lmas3009** [comment]
Sure @priyanshu-gupta0503

**Comment by zainbinfurqan** [comment]
@lmas3009  can you review my PR please

**Comment by siddhant2002** [comment]
Can I work under this issue?

**Comment by siddhant2002** [comment]
Can I work under this issue?

**Comment by lmas3009** [comment]
@siddhant2002 you are already assigned

**Comment by AryanSaxenaa** [comment]
Hey @lmas3009 , Please assign this issue to me, I am interested in this.

**Comment by siddhant2002** [comment]
Raised pr #232 . @lmas3009 Please check the pr.

**Comment by Shreyaprasad02** [comment]
Can you please assign this issue to me @lmas3009

**Comment by lmas3009** [comment]
sure @Shreyaprasad02

**Comment by Shreyaprasad02** [comment]
raised pr #239 @lmas3009 can you please review my pr
