### ISSUE TITLE
[feat]: Create Landing Page - Design Reference Provided

### ISSUE THREAD

**Issue by purnasth** [lmas3009/design2code2live#224]
# Issue Title: Create Landing Page - Design Reference Provided

## Issue Description:
I propose the creation of a landing page that closely follows the design reference provided below. This landing page will be a representation of your profile and your work, enhancing your online presence and showcasing your skills and projects.

## Prerequisites:
- [X] HTML, CSS, and JavaScript.
- [X] Tailwind CSS.

## Design Reference:
![Design Reference](https://cdn.dribbble.com/users/5200396/screenshots/20223138/media/f51b919652cb5b956be2fe1ba9f33714.png)

## Requirements:
- The landing page should closely resemble the design reference, including layout, color scheme, typography, and other design elements.
- Your information, including your name, a brief introduction, contact information, and links to your projects and social profiles, should be integrated into the page.
- The page should be responsive, ensuring that it looks and functions well on various screen sizes and devices.
- You are encouraged to add any additional details, projects, or features that you believe will enhance your personal landing page.

## Rationale:
Creating a personal landing page based on a professional design reference provides a strong online presence and showcases your web development skills. It serves as a valuable portfolio and introduction to your work, helping you stand out and make a positive impression on visitors.

## Additional Information (if available):
If you have specific preferences, additional design elements, or any guidelines for the development of this landing page, please provide them. This will help ensure the landing page accurately represents your vision.

I kindly request that I be assigned to this issue for the creation of my personal landing page.

**Comment by Zenith-17** [comment]
hi please assign this issue to me.

**Comment by bhishekprajapati** [comment]
Hey @purnasth, I'd like to contribute to build this landing page. 
I'm quite experienced with tailwindcss.

Take a look at some of my tailwindcss projects:
* [NFT Portfolio website](https://nft-portfolio.abhishekprajapati.com/)
* [Markdown Editor](http://md-editor.abhishekprajapati.com/)

Consider assigning me to this issue! Thanks!

**Comment by lmas3009** [comment]
@bhishekprajapati create your own landing page and raise a pr. Folder name will be your project name

**Comment by bhishekprajapati** [comment]
Design file?

**Comment by purnasth** [comment]
Hello, @bhishekprajapati you can take any design inspiration from dribble and code it into a beautiful landing page.

**Comment by bhishekprajapati** [comment]
Hey @purnasth, I thought you have a design file. Without a design file it's a lot effort. I can't proceed to work on this issue. Hope you understand. Thanks!
